### ISSUE TITLE
[FEAT] 친구, 스토리태그, 스토리 Entity 설계

### ISSUE THREAD

**Issue by yeseul106** [CDS-Mobile1/CDS_Server#3]
## 📌 Issue

- 친구 , 스토리태그, 스토리 Entity를 개발합니다.

## ✅ Todo
- [x] 친구 Entity 설계
- [x] 스토리태그 Entity 설계
- [x] 스토리 Entity 설계
